ALTER TABLE "analysis_buyer_wallets"
ADD COLUMN IF NOT EXISTS "span_days_in_scope" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "mother_child_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "has_high_fanout_mother" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "matching_confidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "inclusion_decision" TEXT NOT NULL DEFAULT 'included',
ADD COLUMN IF NOT EXISTS "risk_flag" TEXT,
ADD COLUMN IF NOT EXISTS "risk_level" TEXT,
ADD COLUMN IF NOT EXISTS "decision_reasons" JSONB NOT NULL DEFAULT '[]'::jsonb;
